## Importing Libraries  

In [5]:
import pandas as pd #Useful for loading the data set
import numpy as np #To perform array

## Load data 

In [6]:
dataset=pd.read_csv("DigitalAd_dataset.csv")

In [8]:
#dataset set hold the complete information of dataset.
dataset          

Age  Salary  Status
0     18   82000       0
1     29   80000       0
2     47   25000       1
3     45   26000       1
4     46   28000       1
..   ...     ...     ...
395   35   65000       0
396   26   80000       0
397   26   52000       0
398   20   86000       0
399   32   18000       0

[400 rows x 3 columns]

## Summarizing data set

In [12]:
print(dataset.shape) 
print(dataset.head(5))

(400, 3)
   Age  Salary  Status
0   18   82000       0
1   29   80000       0
2   47   25000       1
3   45   26000       1
4   46   28000       1


In [13]:
#Here we are get the complete information of dataset 
#dataset(dataset.shape) - It shows 400 Columns and 3 Rows
#dataset(dataset.shape) - It shows top 5 results of the dataset

## Segregate data into X (input variable) and  (output variale)

In [14]:
X = dataset.iloc[:, :-1].values  

In [15]:
# Here we got the values of X
X 

array([[    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],
       [    27,  17000],
       [    33,  51000],
       [    35, 108000],
       [    30,  15000],
       [    28,  84000],
       [    23,  20000],
       [    25,  79000],
       [    27,  54000],
       [    30, 135000],
       [    31,  89000],
       [    24,  32000],
       [    18,  44000],
       [    29,  83000],
       [    35,  23000],


In [16]:
Y = dataset.iloc[:, -1].values  

In [17]:
# Here we got the values of Y
Y  

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,

## Splitting data set into Train and Test

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
#Here we are passing both input and output seperately using train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.25,random_state=0)

## Feature scalling 

In [20]:
#We scale our data to make all the features contribute equilly to the result.
from sklearn.preprocessing import StandardScaler 

In [21]:
#StandarScalling - By using this method we have rescale our data.
sc=StandardScaler()

In [22]:
#Fit_Transform - fit method is calculating the mean and variance of each of the features present in our data.
X_train=sc.fit_transform(X_train)

In [23]:
#Transform - Transform method is transforming all the features using the respective mean variance.
X_test=sc.transform(X_test)

## Training

In [24]:
#For training process we are using Logistice Regression.
from sklearn.linear_model import LogisticRegression

In [25]:
model=LogisticRegression(random_state=0)

In [26]:
model.fit(X_train,y_train)     

LogisticRegression(random_state=0)

## Predicting , wheather new customer with age and salry will buy on not

In [27]:
Y_pred=model.predict(X_test)

In [28]:
Y_pred

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1], dtype=int64)

##  Predicting , weather with new customer age and salry will buy or not

In [34]:
age = int(input("Enter the age:"))
sal = int(input("Enter the salry:"))
newCust = [[age,sal]]
result = model.predict(sc.transform(newCust))
print(result)
if result ==1:
    print("Customer will but")
else:
    print("Customer won't but")

Enter the age:30
Enter the salry:200000
[1]
Customer will but


## Evaluation MOdel - Confusion Matrix

In [35]:
from sklearn.metrics import confusion_matrix , accuracy_score

In [36]:
print(confusion_matrix(y_test,Y_pred))

[[61  0]
 [20 19]]


In [38]:
print(accuracy_score(y_test,Y_pred)*100)

80.0


## Conclusion - Here we have evaluated our models accuracy is 80.0%